### ISSUE TITLE
Curator should support numpy > 2

### ISSUE THREAD

**Issue by praateekmahajan** [NVIDIA/NeMo-Curator#287] opened 2024-10-09 15:23 UTC
**Is your feature request related to a problem? Please describe.**
Currently [numpy is restricted to < 2](https://github.com/NVIDIA/NeMo-Curator/blob/fa4befcad0a804d9b8ad4a9870b2fd87196d2d26/requirements/requirements.txt#L17). But in cudf 24.10 release [numpy allows 2.0 release](https://github.com/rapidsai/cudf/blob/branch-24.10/python/cudf/pyproject.toml#L28).

However we tried just removing that version pinning, but it ended up in pip being unable to resolve dependencies.

**Describe the solution you'd like**
1. Support numpy 2
2. Be installable with pip

**Describe alternatives you've considered**
1. Tried just removing that pin and installing, but pip wasn't able to resolve packages

**Comment by sarahyurick** [comment] 2024-10-18 20:23
Duplicate of https://github.com/NVIDIA/NeMo-Curator/issues/120.

**Closed by sarahyurick** 2024-10-18 20:23 UTC
Labels: enhancement
