### ISSUE TITLE
Where to obtain domain and quality model files?

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/NeMo-Curator#86] opened 2024-05-28 16:50 UTC
I'm trying to follow the [data classification tutorial](https://github.com/NVIDIA/NeMo-Curator/blob/main/tutorials/distributed_data_classification/distributed_data_classification.ipynb),  which refers to some .pth model files.

Where can I obtain these from? I'd have expected the library to automatically pull them from Hugging Face?

**Comment by ayushdg** [comment] 2024-05-28 18:53
Possibly a duplicate of #72

**Comment by ryantwolf** [comment] 2024-06-24 17:40
Domain classifier available [here](https://huggingface.co/nvidia/domain-classifier/blob/main/model.pth). I will close the issue when we release the quality classifier as well.

**Comment by ryantwolf** [comment] 2024-08-08 18:24
Quality classifier available [here](https://huggingface.co/nvidia/quality-classifier-deberta). Both domain and quality now automatically download from Hugging Face too with #190.

**Closed by ryantwolf** 2024-08-08 18:24 UTC
Labels: bug
